"""phase_1c_recovery_firewall

Revision ID: e4287bb668cc
Revises: fa259d74a0b6
Create Date: 2026-08-31 10:36:57.287333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4287bb668cc'
down_revision: Union[str, Sequence[str], None] = 'fa259d74a0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_policies',
    sa.Column('id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('max_autonomous_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_actions_per_obligation', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('require_human_above_amount', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_policies_merchant_id'), 'recovery_policies', ['merchant_id'], unique=False)
    op.create_table('firewall_evaluations',
    sa.Column('id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('decision_id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('state_version_expected', sa.Integer(), nullable=False),
    sa.Column('state_version_actual', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['recovery_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firewall_evaluations_decision_id'), 'firewall_evaluations', ['decision_id'], unique=False)
    op.create_table('recovery_executions',
    sa.Column('id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('decision_id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('obligation_id', backend.models.UUID(as_uuid=True), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('state_version_at_check', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action'], ['recovery_action_definitions.action_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['recovery_decisions.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['financial_obligations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sample_pkey'))
    )
    op.drop_table('recovery_executions')
    op.drop_index(op.f('ix_firewall_evaluations_decision_id'), table_name='firewall_evaluations')
    op.drop_table('firewall_evaluations')
    op.drop_index(op.f('ix_recovery_policies_merchant_id'), table_name='recovery_policies')
    op.drop_table('recovery_policies')
    # ### end Alembic commands ###
