"""Phase 1D Recovery Execution

Revision ID: eb332e54a9fa
Revises: e4287bb668cc
Create Date: 2026-08-31 11:35:43.561066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models


# revision identifiers, used by Alembic.
revision: str = 'eb332e54a9fa'
down_revision: Union[str, Sequence[str], None] = 'e4287bb668cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_outcomes',
    sa.Column('id', backend.models.UUID(length=32), nullable=False),
    sa.Column('execution_id', backend.models.UUID(length=32), nullable=False),
    sa.Column('obligation_id', backend.models.UUID(length=32), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to_recovery_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('evidence_event_id', backend.models.UUID(length=32), nullable=False),
    sa.Column('attribution_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['razorpay_events.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['recovery_executions.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['financial_obligations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.add_column('recovery_executions', sa.Column('razorpay_reference_id', sa.String(length=40), nullable=True))
    op.add_column('recovery_executions', sa.Column('razorpay_payment_link_id', sa.String(), nullable=True))
    op.add_column('recovery_executions', sa.Column('short_url', sa.String(), nullable=True))
    op.add_column('recovery_executions', sa.Column('payment_link_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'recovery_executions', ['razorpay_payment_link_id'])
    op.create_unique_constraint(None, 'recovery_executions', ['razorpay_reference_id'])
    op.drop_column('recovery_executions', 'external_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_executions', sa.Column('external_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recovery_executions', type_='unique')
    op.drop_constraint(None, 'recovery_executions', type_='unique')
    op.drop_column('recovery_executions', 'payment_link_created_at')
    op.drop_column('recovery_executions', 'short_url')
    op.drop_column('recovery_executions', 'razorpay_payment_link_id')
    op.drop_column('recovery_executions', 'razorpay_reference_id')
    op.drop_table('recovery_outcomes')
    # ### end Alembic commands ###
